/**
 * Email template SQL üretici.
 *
 * Çalıştırma:
 *   pnpm exec tsx scripts/seed-email-templates.ts > scripts/seed-email-templates.sql
 *
 * Çıktı SQL'i sunucuya scp edilir ve psql ile uygulanır:
 *   sshpass -p '...' scp scripts/seed-email-templates.sql root@.../tmp/
 *   ssh <server> 'docker exec -i promtexpress-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB < /tmp/seed-email-templates.sql'
 *
 * Idempotent: aynı (slug, locale) için UPDATE, DB'deki diğer alanları (sentCount, createdAt) korur.
 */
import { renderAll } from "./email-templates/render";

function escSql(s: string): string {
  // PostgreSQL escape: ' → ''; backslash dokunulmaz çünkü standard_conforming_strings=on (default)
  return s.replace(/'/g, "''");
}

const rows = renderAll();
const lines: string[] = [
  "-- Auto-generated by scripts/seed-email-templates.ts",
  "-- Idempotent UPDATE statements for the EmailTemplate table.",
  "-- Run with: docker exec -i promtexpress-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB < this-file.sql",
  "",
  "BEGIN;",
  "",
];

for (const r of rows) {
  lines.push(`-- ${r.slug} | ${r.locale} (subject: ${r.subject})`);
  lines.push(
    `UPDATE "EmailTemplate" SET subject = '${escSql(r.subject)}', "bodyHtml" = '${escSql(r.bodyHtml)}', "bodyText" = '${escSql(r.bodyText)}', "isActive" = true, "updatedAt" = NOW() WHERE slug = '${r.slug}' AND locale = '${r.locale}';`,
  );
  lines.push("");
}

lines.push("-- Verify all 12 rows updated:");
lines.push(
  `SELECT slug, locale, LENGTH("bodyHtml") AS html_len, LENGTH("bodyText") AS text_len FROM "EmailTemplate" ORDER BY slug, locale;`,
);
lines.push("");
lines.push("COMMIT;");

console.log(lines.join("\n"));
