import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Toaster } from "@/components/ui/toaster";
import { PageViewTracker } from "@/components/feature/analytics/page-view-tracker";
import { GoogleAdsTag } from "@/components/feature/analytics/google-ads-tag";
import { ConsentModeUpdater } from "@/components/feature/analytics/consent-mode-updater";
import { PaddleProvider } from "@/components/providers/paddle-provider";
import { ConsentGate } from "@/components/feature/legal/consent-gate";
import { CookieConsentBanner } from "@/components/feature/legal/cookie-consent-banner";
import { SEO_BASE_URL, buildCanonical, buildHreflangMap } from "@/lib/seo/hreflang";
import { JsonLd } from "@/components/seo/json-ld";
import { organizationSchema, websiteSchema } from "@/lib/seo/schemas";
import "./globals.css";

// Cookie-driven locale (NEXT_LOCALE) means cached HTML must not be reused
// across visitors with different locales. Force-dynamic guarantees a fresh
// render per request, which emits `Cache-Control: private, no-cache` — that
// is the actual safeguard preventing shared caches from leaking one locale's
// HTML to another visitor. (Note: a middleware-set `Vary: Cookie` is NOT
// relied upon — Next's RSC vary headers override it in the response pipeline;
// see src/proxy.ts cache-invariant note.) Trade-off: no Full Route Cache
// benefits at the root shell. The cost is acceptable for correct i18n;
// per-page static export can be reintroduced when a future PR moves to fully
// URL-based locales.
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  metadataBase: new URL(SEO_BASE_URL),
  title: {
    default: "PromtExpress — AI Prompt Engineering",
    template: "%s · PromtExpress",
  },
  description:
    "Professional prompt engineering tool. Turn your intent into precision-targeted prompts for ChatGPT, Claude, Gemini, Midjourney, Sora, DALL-E, Suno, and 50+ AI engines.",
  keywords: [
    "prompt engineering",
    "AI prompt generator",
    "ChatGPT prompts",
    "Claude prompts",
    "Midjourney prompts",
    "DALL-E prompts",
    "Sora prompts",
    "Gemini prompts",
    "AI prompt tool",
    "prompt template",
    "Suno prompts",
    "Runway prompts",
    "FLUX prompts",
  ],
  authors: [{ name: "PromtExpress" }],
  creator: "PromtExpress",
  publisher: "PromtExpress",
  applicationName: "PromtExpress",
  category: "technology",
  formatDetection: { email: false, address: false, telephone: false },
  // Keşfedilebilirlik — tüm bot'lara açık
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: buildCanonical("/"),
    languages: buildHreflangMap("/"),
    types: {
      "application/rss+xml": [{ url: "/feed.xml", title: "PromtExpress — RSS" }],
      "application/atom+xml": [{ url: "/atom.xml", title: "PromtExpress — Atom" }],
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SEO_BASE_URL,
    siteName: "PromtExpress",
    title: "PromtExpress — AI Prompt Engineering",
    description:
      "Professional prompt engineering tool. Turn your intent into precision-targeted prompts for 50+ AI engines.",
    // DSK-1: 1200x630 branded card generated by src/app/opengraph-image.tsx.
    // Explicit width/height/type let scrapers render immediately instead of
    // deferring to fetch the asset first. /icon.png (32x32) is the favicon only.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        type: "image/png",
        alt: "PromtExpress — AI Prompt Engineering",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "PromtExpress — AI Prompt Engineering",
    description:
      "Turn your intent into precision-targeted prompts for 50+ AI engines.",
    images: ["/opengraph-image"], // DSK-1: 1200x630 card, not the 32x32 favicon
  },
  icons: {
    icon: [
      { url: "/icon.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION,
    other: {
      ...(process.env.NEXT_PUBLIC_BING_VERIFICATION
        ? { "msvalidate.01": process.env.NEXT_PUBLIC_BING_VERIFICATION }
        : {}),
      ...(process.env.NEXT_PUBLIC_BAIDU_VERIFICATION
        ? { "baidu-site-verification": process.env.NEXT_PUBLIC_BAIDU_VERIFICATION }
        : {}),
    },
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  // <html lang> follows the rendered locale so screen readers + Google read
  // the correct language. Per D1 (2026-05-11) canonical/OG always point to EN
  // even on TR pages (handled in lib/seo/hreflang.ts), but lang must reflect
  // the visible language for accessibility correctness.
  const htmlLang = locale === "tr" ? "tr" : "en-US";
  return (
    <html
      lang={htmlLang}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Plan §7.2 — preconnect to first-paint dependencies. Google Fonts
            preconnects removed (MOB-3): fonts are self-hosted via next/font,
            so those TLS connections were never used. */}
        <link rel="preconnect" href="https://static.cloudflareinsights.com" />
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
        <link rel="dns-prefetch" href="https://cdn.paddle.com" />
      </head>
      <body className="min-h-full flex flex-col bg-bg text-text">
        {/* Plan §7.5 — skip-to-content link (a11y → SEO). */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:px-4 focus:py-2 focus:bg-primary focus:text-primary-text focus:rounded-md focus:shadow-lg"
        >
          Skip to content
        </a>
        <JsonLd data={organizationSchema()} />
        <JsonLd data={websiteSchema()} />
        <NextIntlClientProvider locale={locale} messages={messages}>
        <SessionProvider>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <PaddleProvider>
              {children}
              <Toaster />
              {/* Plan 2026-05-08 step 5 — analytics tracker is gated by user consent. */}
              <ConsentGate category="analytics">
                <Suspense fallback={null}>
                  <PageViewTracker />
                </Suspense>
              </ConsentGate>
              {/*
                Google Consent Mode v2 (Advanced).
                gtag is loaded for ALL users with default 'denied' signals;
                ConsentModeUpdater flips signals to 'granted' when the user
                accepts marketing/analytics cookies. Cookieless pings keep
                flowing in the meantime, recovering 15-25% attribution.
              */}
              <GoogleAdsTag />
              <ConsentModeUpdater />
              <CookieConsentBanner />
            </PaddleProvider>
          </ThemeProvider>
        </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
